default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: startwifi_development

test:
  <<: *default
  database: startwifi_test

production:
  <<: *default
  database: startwifi_production
